-- liquibase formatted sql

-- changeset Homychok:1
CREATE TABLE lot (
                     id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     status  VARCHAR(10) NOT NULL CHECK (status IN ('CREATED', 'STARTED', 'STOPPED')),
                     title VARCHAR(64) NOT NULL,
                     description VARCHAR(4096) NOT NULL,
                     start_price INTEGER NOT NULL,
                     bid_price  INTEGER NOT NULL,
                     current_price  INTEGER,
                     last_bid  varchar(255)
);
-- changeset Homychok:2
ALTER TABLE lot ALTER COLUMN current_price TYPE BIGINT;
-- changeset Homychok:3
ALTER TABLE lot ALTER COLUMN start_price TYPE BIGINT;
ALTER TABLE lot ALTER COLUMN bid_price TYPE BIGINT;
-- changeset Homychok:4
ALTER TABLE lot DROP COLUMN last_bid;
